### ISSUE TITLE
Breaks Admin on 1.7-rc15

### ISSUE THREAD

**Issue by thekenshow** [arkhi/grav-plugin-admin-pages-permissions#3]
Hi - installed this on a 1.7-rc15 system and Admin login no longer completes. The Grav log shows only "Maximum execution time of x seconds exceeded".

**Comment by arkhi** [comment]
Hello,

Thank you for reporting this Issue. This plugin was never tested on 1.7 as that version is not stable. I will had a mention about this and update the blueprint accordingly.

In the meantime, if you know how to solve the issue, I welcome any PR.
